import { type NextPage } from "next";
import Head from "next/head";
import { GameList } from "~/components/gameList";

import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-background flex-col gap-4 flex items-center justify-center overflow-y-auto">
       <GameList></GameList>
      </main>
    </>
  );
};

export default Home;
